### ISSUE TITLE
RE: Versioning

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-acapy-plugin-toolbox#41]
@TelegramSam and I briefly discussed tagging the plugin to show compatibility with ACA-Py versions. I propose we start versioning the plugin at 0.1.0 ASAP and then add tags that potentially point to the same commit of the format `acapy-X.Y.Z-J` where `X.Y.Z` is the ACA-Py version and `J` is an incrementing number for each new plugin release that targets the same version of ACA-Py. I think keeping the versioning independent but still providing the mapping of what plugin versions are compatible with what ACA-Py versions is clearer than having a SemVer nonconforming version or pseudo-lock-step release with ACA-Py.

**Comment by TelegramSam** [comment]
Agree. :) We can start by tagging the 5.3 release this way. We already have a tag, but with a less awesome convention:
https://github.com/hyperledger/aries-acapy-plugin-toolbox/releases/tag/acapy053

**Comment by dbluhm** [comment]
This is now captured in the README so closing this issue
