### ISSUE TITLE
Agent Start Options Not Working

### ISSUE THREAD

**Issue by algarcia-emergya** [hyperledger/aries-acapy-plugin-toolbox#52]
Trying to start agent demos using docker, with/without ngrok, agents go down due to options used in the startup.sh script. 
There is [an issue in the cloudagent repo](https://github.com/hyperledger/aries-cloudagent-python/issues/910)  talking about removed options being used here.

**Comment by dbluhm** [comment]
Thanks for the catch. The agent startup is due a bit of a revamp with the added support for configuration files as well.

**Comment by dbluhm** [comment]
Should be fixed now with #53. Thanks for the report!
