### ISSUE TITLE
Docker Container ngrok exit code 126

### ISSUE THREAD

**Issue by ohmygaugh-crypto** [hyperledger/aries-acapy-plugin-toolbox#57]
demo_agent_1 exits and I get the following: --: ./ngrok-wait.sh: /bin/bash^M: bad interpreter: No such file or directory.

![image](https://user-images.githubusercontent.com/58447309/110229547-55a75f00-7ed8-11eb-8173-41f81ef465f1.png)

I'm using Windows and noticed in the readme there are some limitations for Mac and Windows using ngrok. I thought it was a dos2unix issue, but  I haven't been able to figure that process out. Any tips? Do I need to simply be on a Linux OS?

**Comment by ohmygaugh-crypto** [comment]
phew

**Comment by dbluhm** [comment]
Thanks for the report! We've done fairly extensive testing on Linux and Mac but haven't done much testing on windows lately. I haven't seen this particular issue before but I'll have someone on windows give it a try and see if they hit the same thing. If it's a CRLF issue, is this something that can be solved with git's autocrlf?
