### ISSUE TITLE
Creating a schema with incorrect version triggers agent shutdown

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-acapy-plugin-toolbox#73]
When creating a schema with an incorrect version identifier (e.g. `1` instead of `1.0`) this will trigger a ledger transaction error in ACA-Py, shutting down the agent.

I think it would be good to catch such errors to at least prevent an agent shutdown.

Ledger errors via the Admin API do not trigger shutdown, but ledger errors via protocol messages (as is the case with creating a schema in aries-toolbox) does trigger the shutdown

**Comment by dbluhm** [comment]
Agreed that this definitely shouldn't be causing a shutdown. We'll take a look!

**Comment by dbluhm** [comment]
@burdettadam and @cjhowland took a look at this one today. They weren't able to reproduce the shutdown issue but they did put some frontend checks on the toolbox: https://github.com/hyperledger/aries-toolbox/pull/219.

**Comment by TimoGlastra** [comment]
Thanks for looking into this @burdettadam and @cjhowland. I guess I did something weird that triggered the shutdown. I'll reopen if I run into something like this again
