### ISSUE TITLE
Change ledger being used from Sovrin Staging (sandbox) to Sovrin BuilderNet

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-acapy-plugin-toolbox#91]
With the intention of the Sovrin networks clarified and a new pricing model being applied to StagingNet (Endorsers have a fee), the Toolbox defaults should change from StagingNet to something else -- likely BuilderNet.  This change is going into affect Real Soon Now, so this should be made quickly.

I'm not able to make the changes (long story...) but I think there is a documentation change and the references to the genesis files in the various dockerfiles.

FYI: @dbluhm

**Comment by dbluhm** [comment]
Thanks for the heads up!
